import { useLanguageStore } from "@/store/useLanguageStore";

/** Indonesian for the onboarding copy. The source strings stay English (the values sent to the API
 *  and stored in drafts are untouched); this only changes what is displayed. */
const ID: Record<string, string> = {
  Company: "Perusahaan",
  Information: "Informasi",
  Needs: "Kebutuhan",
  Team: "Tim",
  Back: "Kembali",
  Cancel: "Batal",
  Continue: "Lanjut",
  Finish: "Selesai",
  "Loading…": "Memuat…",
  "Saving…": "Menyimpan…",
  Setup: "Pengaturan awal",
  "Company name is required.": "Nama perusahaan wajib diisi.",
  "Your company name": "Nama perusahaan Anda",
  "This name appears on invoices and documents you issue.": "Nama ini tampil di invoice dan dokumen yang Anda terbitkan.",
  "Company Name": "Nama Perusahaan",
  "e.g. PT Maju Bersama": "mis. PT Maju Bersama",
  "Company information": "Informasi perusahaan",
  "Help us tailor the features for your business.": "Bantu kami menyesuaikan fitur untuk bisnis Anda.",
  Industry: "Bidang Usaha",
  "Select your industry": "Pilih bidang usaha",
  "Select your industry.": "Pilih bidang usaha.",
  "Employee Count": "Jumlah Karyawan",
  "Select employee count": "Pilih jumlah karyawan",
  "Select the employee count.": "Pilih jumlah karyawan.",
  "Company Phone": "Telepon Perusahaan",
  "Company phone number is required.": "Nomor telepon perusahaan wajib diisi.",
  "Company Email": "Email Perusahaan",
  "Company address (optional)": "Alamat perusahaan (opsional)",
  "Street, number, RT/RW": "Jalan, nomor, RT/RW",
  City: "Kota",
  Province: "Provinsi",
  "Postal code": "Kode pos",
  "What do you need most?": "Apa yang paling Anda butuhkan?",
  "Select all that apply. We'll use this to tailor your experience.": "Pilih semua yang sesuai. Kami memakainya untuk menyesuaikan pengalaman Anda.",
  "Select at least one need.": "Pilih minimal satu kebutuhan.",
  "Create sales invoices": "Membuat invoice penjualan",
  "Record purchase bills": "Mencatat tagihan pembelian",
  "Financial reports (balance sheet, P&L)": "Laporan keuangan (neraca, laba rugi)",
  "Manage taxes (VAT/withholding)": "Mengelola pajak (PPN/PPh)",
  "Manage customer & supplier data": "Mengelola data pelanggan & pemasok",
  "Collaborate with a team": "Berkolaborasi dengan tim",
  "Invite your team": "Undang tim Anda",
  "Member email": "Email anggota",
  "Member role": "Peran anggota",
  "Add invitation": "Tambah undangan",
  "Enter an email address.": "Masukkan alamat email.",
  "Invalid email format.": "Format email tidak valid.",
  "Select a member role.": "Pilih peran anggota.",
  "The free invitation quota is full.": "Kuota undangan gratis sudah penuh.",
  "This email is already in the list.": "Email ini sudah ada di daftar.",
  "Skip & finish": "Lewati & selesai",
  "Retail & Trade": "Perdagangan & Ritel",
  Manufacturing: "Manufaktur",
  "Services & Consulting": "Jasa & Konsultasi",
  "Technology / IT": "Teknologi / IT",
  "Food & Beverage (F&B)": "Makanan & Minuman (F&B)",
  "Construction & Real Estate": "Konstruksi & Properti",
  "Logistics & Distribution": "Logistik & Distribusi",
  Other: "Lainnya",
  "1–5 people": "1–5 orang",
  "6–10 people": "6–10 orang",
  "11–25 people": "11–25 orang",
  "26–50 people": "26–50 orang",
  "51–100 people": "51–100 orang",
  "More than 100 people": "Lebih dari 100 orang",
};

export function useOnb() {
  const language = useLanguageStore((s) => s.language);
  return {
    language,
    t: (s: string) => (language === "id" ? (ID[s] ?? s) : s),
    tr: (id: string, en: string) => (language === "id" ? id : en),
  };
}
